# Generated by Django 4.1.5 on 2023-01-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0004_curso_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='comision_curso',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='curso_dicta',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
