# Generated by Django 4.1.5 on 2023-01-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0005_profesor_comision_curso_profesor_curso_dicta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='comision_curso',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
