# Generated by Django 4.1.5 on 2023-01-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0006_alter_profesor_comision_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='comision_curso',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='curso_dicta',
        ),
        migrations.AddField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='comision',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='curso',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
